# Crypto Tracker - Static Analysis & Linter Kuralları
# https://dart.dev/tools/analysis
# https://dart.dev/tools/linter-rules

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    # Style
    prefer_single_quotes: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: false  # Added manually where necessary
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    avoid_redundant_argument_values: true
    avoid_returning_null_for_void: true
    prefer_collection_literals: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    unnecessary_this: true
    use_super_parameters: true

    # Code quality
    avoid_print: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_build_context_synchronously: true
    prefer_typing_uninitialized_variables: true
    require_trailing_commas: false
